package com.myapp.struts;
// Generated 16 Oct, 2014 9:38:22 PM by Hibernate Tools 3.2.1.GA

import org.apache.struts.validator.ValidatorForm;




/**
 * Admin generated by hbm2java
 */
public class Admin extends ValidatorForm implements java.io.Serializable {


     private String uname;
     private String password;

    public Admin() {
    }

	
    public Admin(String uname) {
        this.uname = uname;
    }
    public Admin(String uname, String password) {
       this.uname = uname;
       this.password = password;
    }
   
    public String getUname() {
        return this.uname;
    }
    
    public void setUname(String uname) {
        this.uname = uname;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


