package com.myapp.struts;
// Generated 16 Oct, 2014 9:38:22 PM by Hibernate Tools 3.2.1.GA

import org.apache.struts.validator.ValidatorForm;




/**
 * Clerk generated by hbm2java
 */
public class Clerk extends ValidatorForm implements java.io.Serializable {


     private String uname;
     private String password;
     private String email;
     private String phno;

    public Clerk() {
    }

	
    public Clerk(String uname) {
        this.uname = uname;
    }
    public Clerk(String uname, String password, String email, String phno) {
       this.uname = uname;
       this.password = password;
       this.email = email;
       this.phno = phno;
    }
   
    public String getUname() {
        return this.uname;
    }
    
    public void setUname(String uname) {
        this.uname = uname;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPhno() {
        return this.phno;
    }
    
    public void setPhno(String phno) {
        this.phno = phno;
    }




}


