package com.myapp.struts;
// Generated 16 Oct, 2014 9:38:22 PM by Hibernate Tools 3.2.1.GA




/**
 * Complaint generated by hbm2java
 */
public class Complaint extends org.apache.struts.action.ActionForm  implements java.io.Serializable {


     private int cid;
     private String ctext;
     private String doc;
     private String cuname;
     private String lud;
     private String cse;
     private String adate;
     private String lfeed;
     private String lfd;
     private String status;

    public Complaint() {
    }

	
    public Complaint(int cid) {
        this.cid = cid;
    }
    public Complaint(int cid, String ctext, String doc, String cuname, String lud, String cse, String adate, String lfeed, String lfd, String status) {
       this.cid = cid;
       this.ctext = ctext;
       this.doc = doc;
       this.cuname = cuname;
       this.lud = lud;
       this.cse = cse;
       this.adate = adate;
       this.lfeed = lfeed;
       this.lfd = lfd;
       this.status = status;
    }
   
    public int getCid() {
        return this.cid;
    }
    
    public void setCid(int cid) {
        this.cid = cid;
    }
    public String getCtext() {
        return this.ctext;
    }
    
    public void setCtext(String ctext) {
        this.ctext = ctext;
    }
    public String getDoc() {
        return this.doc;
    }
    
    public void setDoc(String doc) {
        this.doc = doc;
    }
    public String getCuname() {
        return this.cuname;
    }
    
    public void setCuname(String cuname) {
        this.cuname = cuname;
    }
    public String getLud() {
        return this.lud;
    }
    
    public void setLud(String lud) {
        this.lud = lud;
    }
    public String getCse() {
        return this.cse;
    }
    
    public void setCse(String cse) {
        this.cse = cse;
    }
    public String getAdate() {
        return this.adate;
    }
    
    public void setAdate(String adate) {
        this.adate = adate;
    }
    public String getLfeed() {
        return this.lfeed;
    }
    
    public void setLfeed(String lfeed) {
        this.lfeed = lfeed;
    }
    public String getLfd() {
        return this.lfd;
    }
    
    public void setLfd(String lfd) {
        this.lfd = lfd;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


