package com.myapp.struts;
// Generated 16 Oct, 2014 9:38:22 PM by Hibernate Tools 3.2.1.GA




/**
 * Solution generated by hbm2java
 */
public class Solution extends org.apache.struts.action.ActionForm implements java.io.Serializable {


     private int sid;
     private String sdate;
     private String soltext;
     private String cse;
     private String cuname;

    public Solution() {
    }

	
    public Solution(int sid) {
        this.sid = sid;
    }
    public Solution(int sid, String sdate, String soltext, String cse, String cuname) {
       this.sid = sid;
       this.sdate = sdate;
       this.soltext = soltext;
       this.cse = cse;
       this.cuname = cuname;
    }
   
    public int getSid() {
        return this.sid;
    }
    
    public void setSid(int sid) {
        this.sid = sid;
    }
    public String getSdate() {
        return this.sdate;
    }
    
    public void setSdate(String sdate) {
        this.sdate = sdate;
    }
    public String getSoltext() {
        return this.soltext;
    }
    
    public void setSoltext(String soltext) {
        this.soltext = soltext;
    }
    public String getCse() {
        return this.cse;
    }
    
    public void setCse(String cse) {
        this.cse = cse;
    }
    public String getCuname() {
        return this.cuname;
    }
    
    public void setCuname(String cuname) {
        this.cuname = cuname;
    }




}


